org: indievoiceapp
app: jovowebpack
service: alexa2

# Create an optimized package for our functions
package:
  individually: true
  excludeDevDependencies: true

plugins:
  #- serverless-plugin-ncc
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    sourcemaps: false
  ncc:
    minify: false
    source-map: false
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  profile: iva-serverless
  skill:
    name: ${self:org}-${self:app}-${self:custom.currentStage}
    id: amzn1.ask.skill.19125de2-948f-4d7d-9df6-73afcc3e28c2
  defaultStage: dev
  defaultRegion: eu-central-1
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${opt:region, self:custom.defaultRegion}
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  profile: ${self:custom.profile}
  stackName: ${self:app}-${self:service}-${self:custom.currentStage}
  apiName: ${self:app}-${self:service}-${self:custom.currentStage}
  memorySize: 128

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    stage: ${self:custom.currentStage}

  httpApi:
    cors: true

functions:
  alexa:
    name: ${self:custom.skill.name}
    handler: src/index.handler
    events:
      - alexaSkill: ${self:custom.skill.id}
      - httpApi:
          method: POST
          path: /alexa
